DROP TABLE PERSONA_GRUPO_INV
DROP TABLE PROYECTO_PERSONA
DROP TABLE ENTREGABLE_INFORME
DROP TABLE PROYECTO_PLANTA
DROP TABLE INSTITUCION_ACTIVIDAD
DROP TABLE GRUPO_INV
DROP TABLE PERSONA
DROP TABLE PLANTA_SITIO
DROP TABLE PLANTA
DROP TABLE SITIO
DROP TABLE ENTREGABLE
DROP TABLE INFORME_ACTIVIDAD
DROP TABLE INFORME
DROP TABLE TAREA
DROP TABLE ACTIVIDAD
DROP TABLE INSTITUCION
DROP TABLE PROYECTO
DROP TABLE USUARIO

CREATE TABLE PROYECTO
(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(255)						 ,
    TIPO VARCHAR(255) NOT NULL ,
    FASE_INV_TRAS VARCHAR(255),
    ETAPA VARCHAR(255),
    TAGS VARCHAR(255),
    URL_IMAGEN VARCHAR(750)
)

CREATE TABLE ACTIVIDAD
(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    PROYECTO_ID BIGINT NOT NULL FOREIGN KEY REFERENCES PROYECTO(ID),
    DESCRIPCION VARCHAR(750),
    TIPO VARCHAR(255),
    OBJETIVO_POFI VARCHAR(750),     
    NUMERO VARCHAR(8) NOT NULL
)
--1234 5 67 8 910
CREATE TABLE TAREA
(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    ACTIVIDAD_ID BIGINT NOT NULL FOREIGN KEY REFERENCES ACTIVIDAD(ID),
    DESCRIPCION VARCHAR(750),
    FECHA_INICIO VARCHAR (10),
    FECHA_FIN VARCHAR (10),
    PORCENTAJE_AVANCE FLOAT NOT NULL,
    DURACION_MESES FLOAT NOT NULL,
    FECHA_INICIO_REAL VARCHAR (10),
    FECHA_FINAL_REAL VARCHAR (10)
)

CREATE TABLE ENTREGABLE
(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(750) NOT NULL,
    SUBPRODUCTO VARCHAR(750) ,
    TIPO VARCHAR(750) NOT NULL,
    PRODUCTO VARCHAR(750) ,
    ANO_PROYECCION INT 
)

CREATE TABLE INSTITUCION
(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    ACRONIMO VARCHAR(255),
    TIPO VARCHAR(255),
    TIPO_ORG VARCHAR(255),
    PRESUPUESTO FLOAT,
    URL_IMAGEN VARCHAR(750)
)

CREATE TABLE INFORME
(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    PROYECTO_ID BIGINT NOT NULL FOREIGN KEY REFERENCES PROYECTO(ID) ,
    FECHA_CORTE VARCHAR (10)
)

CREATE TABLE ENTREGABLE_INFORME
(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    INFORME_ID BIGINT NOT NULL FOREIGN KEY REFERENCES INFORME(ID),
    ENTREGABLE_ID BIGINT NOT NULL FOREIGN KEY REFERENCES ENTREGABLE(ID),
    PORCENTAJE_AVANCE FLOAT NOT NULL
)

CREATE TABLE INFORME_ACTIVIDAD
(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    ACTIVIDAD_ID BIGINT NOT NULL FOREIGN KEY REFERENCES ACTIVIDAD(ID) ,
    INFORME_ID BIGINT NOT NULL FOREIGN KEY REFERENCES INFORME(ID),
    PORCENTAJE_AVANCE FLOAT NOT NULL
)

CREATE TABLE PERSONA
(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    ROL VARCHAR(255) ,
    ROL_PROGRAMA VARCHAR(255) ,
    NIVEL_ACADEMICO VARCHAR(255) ,
    CATEGORIA_INV VARCHAR(255) ,
    TIPO VARCHAR(255) ,
    FUNCIONES VARCHAR(750) ,
    FORMACION VARCHAR(750) ,
    CVLAC VARCHAR(255) ,
    GRUPO_LAC VARCHAR(255) ,
    IS_ACTIVE INT,
    INSTITUCION_ID BIGINT FOREIGN KEY REFERENCES INSTITUCION(ID),
    URL_IMAGEN VARCHAR(8000),
    GENERO VARCHAR(255)

)

CREATE TABLE PROYECTO_PERSONA
(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    PERSONA_ID BIGINT NOT NULL FOREIGN KEY REFERENCES PERSONA(ID) ,
    PROYECTO_ID BIGINT NOT NULL FOREIGN KEY REFERENCES PROYECTO(ID),
    FECHA_ACTUALIZACION VARCHAR (10)
)

CREATE TABLE GRUPO_INV
(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    TIPO VARCHAR(255),
    CLASIFICACION_COLCIENCIAS VARCHAR(255),
    INSTITUCION_ID BIGINT NOT NULL FOREIGN KEY REFERENCES INSTITUCION(ID),
    TAGS VARCHAR(750)
)

CREATE TABLE PERSONA_GRUPO_INV
(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    GRUPO_INV_ID BIGINT NOT NULL FOREIGN KEY REFERENCES GRUPO_INV(ID),
    PERSONA_ID BIGINT NOT NULL FOREIGN KEY   REFERENCES PERSONA(ID),
    FECHA_ACTUALIZACION VARCHAR (10)
)

CREATE TABLE SITIO
(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    LATITUD DECIMAL(18,10) NOT NULL,
    LONGITUD DECIMAL(18,10)  NOT NULL
)

INSERT INTO SITIO VALUES ('Amazonas',-1.0197222,-71.9383333)
INSERT INTO SITIO VALUES ('Antioquia',7,-75.5)
INSERT INTO SITIO VALUES ('Arauca',7.0902778,-70.7616667)
INSERT INTO SITIO VALUES ('Atlántico',10.75,-75)
INSERT INTO SITIO VALUES ('Bolivar',9,-74.3333333)
INSERT INTO SITIO VALUES ('Boyacá',5.5,-72.5)
INSERT INTO SITIO VALUES ('Caldas',5.25,-75.5)
INSERT INTO SITIO VALUES ('Caqueta',1,-74)
INSERT INTO SITIO VALUES ('Casanare',5.5,-71.5)
INSERT INTO SITIO VALUES ('Cauca',2.5,-76.8333333)
INSERT INTO SITIO VALUES ('Cesar',9.3333333,-73.5)
INSERT INTO SITIO VALUES ('Choco',6,-77)
INSERT INTO SITIO VALUES ('Cundinamarca',5,-74.1666667)
INSERT INTO SITIO VALUES ('Córdoba',8.3333333,-75.6666667)
INSERT INTO SITIO VALUES ('Guainía',2.5,-69)
INSERT INTO SITIO VALUES ('Guaviare',1.6894444,-72.8202778)
INSERT INTO SITIO VALUES ('Huila',2.5,-75.75)
INSERT INTO SITIO VALUES ('La Guajira',11.5,-72.5)
INSERT INTO SITIO VALUES ('Magdalena',10,-74.5)
INSERT INTO SITIO VALUES ('Meta',3.5,-73)
INSERT INTO SITIO VALUES ('Nariño',1.5,-78)
INSERT INTO SITIO VALUES ('Norte de Santander',8,-73)
INSERT INTO SITIO VALUES ('Putumayo',0.5,-76)
INSERT INTO SITIO VALUES ('Quindío',4.5,-75.6666667)
INSERT INTO SITIO VALUES ('Risaralda',5,-76)
INSERT INTO SITIO VALUES ('San Andrés',12.5847222,-81.7005556)
INSERT INTO SITIO VALUES ('Santander',7,-73.25)
INSERT INTO SITIO VALUES ('Sucre',9,-75)
INSERT INTO SITIO VALUES ('Tolima',3.75,-75.25)
INSERT INTO SITIO VALUES ('Valle',3.75,-76.5)
INSERT INTO SITIO VALUES ('Vaupés',0.25,-70.75)
INSERT INTO SITIO VALUES ('Vichada',5,-69.5)
INSERT INTO SITIO VALUES ('Bogotá',4.6,-74.0833333)

CREATE TABLE PLANTA
(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    TIPO VARCHAR(255) NOT NULL,
    ORIGEN VARCHAR(255),
    SITIO_UNICO_OBT_ID BIGINT NOT NULL FOREIGN KEY REFERENCES SITIO(ID),
    REG_INVIMA VARCHAR(750),
    REG_INTERNACIONAL VARCHAR(750),
	ENCARGADO_RECOLECTA VARCHAR(750)
)

CREATE TABLE PLANTA_SITIO
(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    PLANTA_ID BIGINT NOT NULL FOREIGN KEY REFERENCES PLANTA(ID),
    SITIO_ID BIGINT NOT NULL FOREIGN KEY REFERENCES SITIO(ID),
)

CREATE TABLE PROYECTO_PLANTA
(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    PROYECTO_ID BIGINT NOT NULL FOREIGN KEY REFERENCES PROYECTO(ID),
    PLANTA_ID BIGINT NOT NULL FOREIGN KEY REFERENCES PLANTA(ID),
    FECHA_ACTUALIZACION VARCHAR (10)
)

CREATE TABLE INSTITUCION_ACTIVIDAD
(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    ACTIVIDAD_ID BIGINT NOT NULL FOREIGN KEY REFERENCES ACTIVIDAD(ID),
    INSTITUCION_ID BIGINT NOT NULL FOREIGN KEY REFERENCES INSTITUCION(ID),
    FECHA_ACTUALIZACION VARCHAR (10)
)

CREATE TABLE USUARIO
(
    ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    ESTADO VARCHAR(255) NOT NULL,
    ROL VARCHAR(255) NOT NULL
)